---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r}
data("ny_noaa")
df = ny_noaa |> 
  drop_na() |> 
  filter (snow >= 0) |> 
  mutate(
    tmin = as.numeric(tmin),
    tmax = as.numeric(tmax))
```


Column {data-width=500}
-----------------------------------------------------------------------

### The Maximun Temperature in the Weather Station(USC00305512) from 2000 to 2010

```{r}
df |> mutate(year = year(date)) |> 
  filter((id == "USC00305512") & (year %in% c(2000:2010))) |> 
  mutate(year = as.factor(year)) |> 
  plot_ly(
    x = ~year, y = ~tmax, color = ~as.factor(year),
    type = "box") |> 
  layout(legend = list(
          orientation = "h",      
          x = 0.5,                
          xanchor = "center",
          y = -0.2              
        ))

```


Column {data-width=500}
-----------------------------------------------------------------------

### Tmax v.s. Tmin in the Weather Station(USC00305512) in year 2010

```{r}
df |> 
  filter(
    (id == "USC00306184") & (year(date) %in% 2010)) |> 
  mutate(
    text_label = 
           str_c("Date: ", date, 
                 "\nMaximum Tempterature: ", tmax, 
                 "\nMinimum Tempterature: ", tmin)) |> 
  plot_ly(
    x = ~tmin, y = ~tmax, text = ~text_label,
    type = "scatter", mode = "markers", alpha = .5
  )

```

### The Number of Snowy Day in Different Weather Stations in 2010

```{r}
df |> 
  filter((year(date) == 2010) & (snow >0)) |> 
  count(id) |> 
  mutate(id = fct_reorder(id,n)) |> 
  plot_ly(
    x = ~id, y = ~n,
    type = "bar") 
```
